# 基本概念

### TensorFlow 张量
在数学里，张量是一种几何实体，广义上表示任意形式的“数据”。张量可以理解为0阶（rank）标量、1阶向量和2阶矩阵在高维空间上的推广，张量的阶描述它表示数据的最大维度。

| 阶      | 数据实体     | python 样例 |
| :-----: | :---------: | :----------: |
| 0       | 标量         | scalar = 1  |
| 1       | 向量         | vector = [1,2,3]|
| 2       | 矩阵（数据表）| matrix = [[1,2,3],[4,5,6],[7,8,9]] |
| 3       | 数据立方     | tensor = [[[1],[2],[3]], [[1],[2],[3]],[[1],[2],[3]],...]|
| 4       | n阶张量      | ... |
![tensor-dimension.png](./images/tensor-dimension.png)

在 TensorFlow 中，张量（Tensor）表示某种相同类型的多维数组。因此，张量有两个重要属性：
1. 数据类型（如浮点型、整整、字符串）
- 数组形状（各个维度的大小）

TensorFlow中几类特殊的张量及产生方式：
1. 常量：不能修改的数据，tf.constant
2. 占位符：数据流程图图外输入的数据， tf.placeholder
3. 变量：执行操作时可以修改的数据，tf.Variable

###### Notes:
- 张量是用来表示多维数据的
- 张量是执行操作时的输入和输出数据
- 用户通过执行操作来创建或计算张量
- 张量的形状不一定在编译时确定，可以在运行时通过形状推断计算得出

#### 练习

In [1]:
import tensorflow as tf

In [15]:
# 0 阶张量
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

In [16]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable_32:0' shape=() dtype=string_ref>,
 <tf.Variable 'Variable_33:0' shape=() dtype=int32_ref>,
 <tf.Variable 'Variable_34:0' shape=() dtype=float32_ref>,
 <tf.Variable 'Variable_35:0' shape=() dtype=complex128_ref>]

In [17]:
# 1阶张量
mystr = tf.Variable(["Hello", "World"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71888], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 9, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.75j, 7.5 - 6.23j], tf.complex64)

In [18]:
[mystr, cool_numbers, first_primes, its_very_complicated]

[<tf.Variable 'Variable_36:0' shape=(2,) dtype=string_ref>,
 <tf.Variable 'Variable_37:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'Variable_38:0' shape=(6,) dtype=int32_ref>,
 <tf.Variable 'Variable_39:0' shape=(2,) dtype=complex128_ref>]

In [33]:
# 2阶张量
mymat = tf.Variable([[7], [11]], tf.int16)
myxor = tf.Variable([[False, True], [True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7], [11]], tf.int32)
more_squares = tf.Variable([[[4, 9, 1], [1, 2, 3]], [[16, 25, 1], [1, 2, 3]]], tf.int32)

In [34]:
[mymat, myxor, linear_squares, squarish_squares, rank_of_squares, mymatC, more_squares]

[<tf.Variable 'Variable_57:0' shape=(2, 1) dtype=int32_ref>,
 <tf.Variable 'Variable_58:0' shape=(2, 2) dtype=bool_ref>,
 <tf.Variable 'Variable_59:0' shape=(4, 1) dtype=int32_ref>,
 <tf.Variable 'Variable_60:0' shape=(2, 2) dtype=int32_ref>,
 <tf.Tensor 'Rank_3:0' shape=() dtype=int32>,
 <tf.Variable 'Variable_61:0' shape=(2, 1) dtype=int32_ref>,
 <tf.Variable 'Variable_62:0' shape=(2, 2, 3) dtype=int32_ref>]

In [35]:
# 4阶张量
my_image = tf.zeros([10, 299, 299, 3])

In [32]:
my_image

<tf.Tensor 'zeros:0' shape=(10, 299, 299, 3) dtype=float32>

### TensorFlow 变量
TensorFlow 变量（Variable）的主要作用是维护特定节点的状态，如深度学习或机器学习的模型参数。

tf.Variable 方式是操作，返回值是变量（特殊张量）

通过tf.Variable 方法创建的变量，与张量一样可以作为操作的输入和输出，不同之处在于：
- 张量的生命周期通常随依赖的计算完成而结束，内存也随即释放
- 变量则常驻内存，在每一步训练时不断更新其值，以实现模型参数的更新

###### 使用示例

```PYTHON
import tensorflow as tf

# 创建变量
w = tf.Variable(<initial-value>, name=<optional-name>)

# 将变量作为操作的输入
y = tf.matmul(w, ...another variable or tensor...)
z = tf.sigmoid(w + y)

# 使用 assign 或 assign_xxx 方法重新给变量赋值
w.assign(w + 1.0)
w.assign_add(1.0)
```

###### Saver 使用示例
```PYTHON
v1 = tf.Variable(..., name='v1')
v2 = tf.Variable(..., name='v2')

# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': v1, 'v2': v2})
saver = tf.train.Saver([v1, v2]) # key 值由上面 tf.Variable 函数中的 name 决定
saver = tf.train.Saver({v.op.name: v for v in [v1, v2]}) # 第二个操作的显示操作

# 保存变量的方法
tf.train.saver.save(sess, 'my-model', global_step=0) # ==> filename: 'my-model-0'
```

###### TensorFlow 变量使用流程
![variable-use-flow.png](./images/variable-use-flow.png)

练习

In [2]:
import tensorflow as tf

In [4]:
# 创建变量
# tf.random_normal 方法返回形状为（1，4）的张量。它的4个元素符合均值为100、标准差为0.35的正态分布
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name="W")
b = tf.Variable(tf.zeros([4]), name="b")

In [5]:
[W, b]

[<tf.Variable 'W_1:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b_1:0' shape=(4,) dtype=float32_ref>]

In [6]:
# 初始化变量
# 创建会话（之后小节介绍）
sess = tf.Session()
# 使用 global_variables_initializer 方法初始化全局变量 W 和 b
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])

[array([[100.092926,  99.65607 ,  99.66742 ,  99.849396]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [7]:
# 执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))

array([1., 1., 1., 1.], dtype=float32)

In [8]:
# 查看变量 b 是否更新成功
sess.run(b)

array([1., 1., 1., 1.], dtype=float32)

从文件中恢复变量

In [9]:
# 创建 Saver
saver = tf.train.Saver({'W': W, 'b': b})
# 存储变量到文件 './summary/test.ckpt-0'
saver.save(sess, './summary/test.ckpt', global_step=0)

'./summary/test.ckpt-0'

In [10]:
# 再次执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))
# 获取变量 b 的最新值
sess.run(b)

array([2., 2., 2., 2.], dtype=float32)

In [13]:
# 从文件中恢复变量 b 的值
saver.restore(sess, './summary/test.ckpt-0')
# 查看变量 b 是否恢复成功
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([1., 1., 1., 1.], dtype=float32)

In [15]:
# 从文件中恢复数据流图结构
# tf.train.import_meta_graph

### TensorFlow 操作
TensorFlow 用数据流图表示算法模型。数据流图由 **节点** 和 **有向边** 组成，每个节点均对应一个具体的操作。因此，操作是模型功能的实际载体。

数据流图中的节点按照功能不同可以分为3种：
- **存储节点：** 有状态的变量操作，通常用来存储模型参数
- **计算节点：** 无状态的计算或控制操作，主要负责算法逻辑表达或流程控制
- **数据节点：** 数据的占位符操作，用户描述图外输入数据的属性

**操作的输入和输出是张量或操作（函数式变成）**

TensorFlow 典型计算和控制操作
![operations.png](./images/operations.png)

### TensorFlow 占位符操作
TensorFlow 使用占位符操作表示图外输入的数据，如训练和测试数据。
TensorFlow 数据流图描述了算法模型的计算拓扑，其中的各个操作（节点）都是抽象的函数映射或数学表达式。
换句话说，数据流图本身是一个具有计算拓扑和内部接口的”壳“。在用户向数据流图填充数据前，图中并没有真正执行任何计算。
```PYTHON
# x = tf.placeholder(dtype, shape, name)
x = tf.placeholder(tf.int16, shape=(), name="x")
y = tf.placeholder(tf.int16, shape=(), name="y")
with tf.Session() as sess:
    # 填充数据后，执行操作
    print(sess.run(add, feed_dict={x: 2, y: 3}))
    print(sess.run(mul, feed_dict={x: 2, y: 3}))
```

练习

In [16]:
import tensorflow as tf

In [19]:
# 常量操作
a = tf.constant(2)
b = tf.constant(3)

In [20]:
# 创建会话，并执行计算操作
with tf.Session() as sess:
    print("a: %i" % sess.run(a))
    print("b: %i" % sess.run(b))
    print("Addition with constants: %i" % sess.run(a + b))
    print("Multiplication with constants: %i" % sess.run(a * b))

a: 2
b: 3
Addition with constants: 5
Multiplication with constants: 6


In [21]:
# 占位符操作
# x = tf.placeholder(dtype, shape, name)
x = tf.placeholder(tf.int16, shape=(), name="x")
y = tf.placeholder(tf.int16, shape=(), name="y")

In [22]:
# 计算操作
add = tf.add(x, y)
mul = tf.multiply(x, y)

In [23]:
# 加载默认数据流图
with tf.Session() as sess:
    # 不填充数据，直接执行操作，报错
    print("Addition with variables: %i" % sess.run(add))
    print("Multipication with variables: %i" % sess.run(mul))

InvalidArgumentError: You must feed a value for placeholder tensor 'x' with dtype int16
	 [[node x (defined at <ipython-input-21-818eb793cb50>:3) ]]

Caused by op 'x', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-818eb793cb50>", line 3, in <module>
    x = tf.placeholder(tf.int16, shape=(), name="x")
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2077, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5791, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/sivan/work/tensorflow-work2/tensorflow-venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'x' with dtype int16
	 [[node x (defined at <ipython-input-21-818eb793cb50>:3) ]]


In [24]:
# 加载默认数据流图
with tf.Session() as sess:
    # 填充数据
    print("Addition with variables: %i" % sess.run(add, feed_dict={x: 2, y: 3}))
    print("Multipication with variables: %i" % sess.run(mul, feed_dict={x: 2, y: 3}))

Addition with variables: 5
Multipication with variables: 6


### TensorFlow 会话
会话提供了估算张量和执行操作的 **运行环境** ，它是发放计算任务的客户端，所有计算任务都由它连接的执行引擎完成。一个会话的典型使用流程分为以下3步：
```PYTHON
# 1.创建会话 target: 会话连接的执行引擎；graph: 会话加载的数据流图；config: 会话启动时的配置项
sess = tf.Session(target=..., graph=..., config=...)
# 2.估算张量或执行操作
sess.run(...)
# 3.关闭会话
sess.close()
```

###### 会话执行操作示例
```PYTHON
import tensorflow as tf
# 创建数据流图 z = x * y
x = tf.placeholder(tf.float32, name='x')
y = tf.placeholder(tf.float32, nmae='y')
z = tf.multiply(x, y, name='z')
sess = tf.Session()
print(sess.run(z, feed_dict={x: 3.0, y: 2.0}))
'''
输出6.0
'''
```
###### 会话估算张量示例
```PYTHON
import tensorflow as tf
# 创建数据流图 c = a + b
a = tf.constant(1.0, name='a')
b = tf.constant(2.0, name='b')
c = tf.add(a, b, name='c')
sess = tf.Session()
print(sess.run(c))
'''
输出3.0
'''
```

获取张量值得另外两种方法：估算张量（Tensor.eval）与执行操作（Operation.run）
###### 示例
```PYTHON
import tensorflow as tf
# 创建数据流图：y = W * x + b, 其中 W 和 b 为存储节点，x 为数据节点
x = tf.placeholder(tf.float32)
W = tf.Variable(1.0)
b = tf.Variable(1.0)
y = W * x + b
with tf.Session() as sess:
    tf.global_variables_initializer().run() # Operation.run
    fetch = y.eval(feed_dict={x: 3.0})      # Tensor.eval
    print(fetch)                            # fetch = 1.0 * 3.0 + 1.9
```

### TensorFlow 会话执行原理
当我们调用 sess.run(train_op) 语句执行训练操作时：
1. 首先，程序内部提取操作依赖的所有前置操作。这些操作的节点共同组成一幅子图
- 然后，程序会将子图中的计算节点，存储节点和数据节点按照各自的执行设备分类，相同设备的节点组成了一幅局部图
- 最后，每个设备上的局部图在实际执行时，根据节点间的依赖关系将各个节点有序地加载到设备上执行
![session-principle.png](./images/session-principle.png)

对于单机程序来说，相同机器上不同编号的 CPU 或 GPU 就是不同的设备，我们可以在创建节点时指定执行该节点的设备
```PYTHON
# 在0号 CPU 执行的存储节点
with tf.device("/cpu:0"):
    v = tf.Variable(...)
    
# 在0号 GPU 执行的计算节点
with tf.device("/gpu:0"):
    z = tf.matmul(x, y)
```